Update 01-firstworkflow.yaml

diff --git a/.github/workflows/01-firstworkflow.yaml b/.github/workflows/01-firstworkflow.yaml
--- a/.github/workflows/01-firstworkflow.yaml
+++ b/.github/workflows/01-firstworkflow.yaml
@@ -1,6 +1,11 @@
 name: 01-first workflow
 on: 
   push:
+    branches-ignore:
+      - main
+  pull_request:
+    branches:
+      - main
   workflow_dispatch:
     inputs:
       branch: 
@@ -11,5 +16,21 @@ jobs:
   echo-hello:
     runs-on: ubuntu-latest
     steps:
-      - name: Print Hello
-        run: echo "Hello world"
+      - name: Trigger
+        run: echo "Triggered by ${{github.event_name}} event"
+      - name: Check Branch Input
+        run: |
+          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
+            if [ -z "${{ github.event.inputs.branch }}" ]; then
+              echo "Branch input is required for manual trigger."
+              exit 1
+            fi
+          fi              
+      - name: Checkout
+        uses: actions/checkout@v4.1.7
+        with:
+          ref: "${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || github.ref }}" 
+      - name: Log Current Branch and Commit
+        run: |
+          echo "Current branch: $(git rev-parse --abbrev-ref HEAD)"
+          echo "Current commit: $(git rev-parse HEAD)"
